require 'date'
require 'simplecov'
SimpleCov.start
require_relative '../lib/cipher'
require_relative '../lib/date'
# require_relative '../lib/decrypt'
# require_relative '../lib/encrypt'
require_relative '../lib/enigma'
require_relative '../lib/shift_generator'
require_relative '../lib/message'
